apiVersion: v1
kind: Template
labels:
  template: openshift-eclipse-che
  group: cicd
metadata:
  annotations:
    iconClass: icon-eclipse-che
    tags: instant-app,jenkins,gogs,nexus,cicd,openshift-eclipse-che,che,devops,ide
    displayName: "Eclipse Che - Single User"
    description: "Eclipse Che makes OpenShift development accessible for developer teams, providing one-click developer workspaces and eliminating local environment configuration for your entire team. Che brings your OpenShift application into your development environment and provides an in-browser IDE, allowing you to code, build, test and run applications exactly as they run on production from any machine."
    openshift.io/display-name: "Eclipse Che - Single User"
  name: openshift-eclipse-che
objects:

- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    name: default_admin
  roleRef:
    name: admin
  subjects:
  - kind: ServiceAccount
    name: default
    
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: openshift-eclipse-che-installer
  spec:
    activeDeadlineSeconds: 400
    completions: 1
    parallelism: 1
    template:
      spec:
        containers:
          - command:
              - /bin/bash
              - '-x'
              - '-c'
              - >
                oc new-app --template=jenkins-ephemeral -l tracker=tempJenkins && \

                oc set resources dc/jenkins --limits=memory=1Gi --requests=memory=512Mi && \

                oc label dc jenkins app=jenkins --overwrite && \

                HOSTNAME=$(oc get route jenkins -o template --template='{{.spec.host}}' | sed "s/jenkins-${CHE_NAMESPACE}.//g") && \

                oc process -f https://raw.githubusercontent.com/epe105/minishift-addons/master/add-ons/che/templates/che-single-user.yml \
                  --param PROJECT_NAME=$CHE_NAMESPACE \
                  --param DOMAIN_NAME=$HOSTNAME \
                  --param OPENSHIFT_OAUTH_TOKEN="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
                  | oc create -f - && \
                oc set resources dc/che --limits=cpu=1,memory=2G --requests=cpu=200m,memory=512Mi && \

                oc delete all --selector app=jenkins --selector tracker=tempJenkins
            env:
              - name: CHE_NAMESPACE
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
            image: 'openshift/origin:v3.11.0'
            imagePullPolicy: IfNotPresent
            name: che-demo-installer-job
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        restartPolicy: Never
